{"name": "test_login_with_wrong_password_shows_error", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "test\\test_login.py:21: in test_login_with_wrong_password_shows_error\n    err = page.get_error()\n          ^^^^^^^^^^^^^^^^\ntest\\pages\\login_page.py:55: in get_error\n    error_elements = self.find_elements(self.ALL_ERRORS)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\ntest\\pages\\base_page.py:20: in find_elements\n    return self.wait.until(expected_conditions.presence_of_all_elements_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nC:\\Users\\Admin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\selenium\\webdriver\\support\\wait.py:138: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:"}, "start": 1755846718668, "stop": 1755846730066, "uuid": "d8ac07cd-8d33-48cd-bdb1-37009c3289e0", "historyId": "c4df2a0a74b86b195505efe951f3735b", "testCaseId": "c4df2a0a74b86b195505efe951f3735b", "fullName": "test.test_login#test_login_with_wrong_password_shows_error", "labels": [{"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-1OFPU5R"}, {"name": "thread", "value": "8820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login"}], "titlePath": ["test", "test_login.py"]}